---
title: "Cluster Overlap Function"
output: html_document
date: "2025-1-14"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r Load data}
Pop1 <- read.csv("/work/lotterhos/2020_CodGenomes_Inversions/outputs/Pop1_INV.csv")
Pop1.PCA <- Pop1[Pop1$PROGRAM=="PCA", ] #Stored just in case; for now, doing overlap test without PCA
Pop1 <- subset(Pop1, Pop1$PROGRAM != "PCA")

```

```{r Create a function to run overlap test on the start position of the inversion}
#Function to complete the overlap test
overlap_test <- function(dataframe){
  #Create empty matrix to store results of overlap test
  mat <- matrix(ncol = nrow(dataframe), nrow = nrow(dataframe))
  
  #Evaluate different scenarios of overlapping
  for (i in 1:nrow(dataframe)) {
    for (j in 1:nrow(dataframe)) {
      I1_lower <- dataframe$POS_MINUS_CI[i]
      I1_upper <- dataframe$POS_PLUS_CI[i]
    
      I2_lower <- dataframe$POS_MINUS_CI[j]
      I2_upper <- dataframe$POS_PLUS_CI[j]
    
      mat[i,j] <- if(I2_lower <= I1_lower){
        I2_upper >= I1_lower | I2_upper >= I1_upper
        } else if (I2_upper >= I1_upper){
          I2_lower <= I1_upper
          } else if (I2_upper <= I1_upper){
            I2_upper >= I1_lower
            }
    }
  }
  
  #Return the matrix storing results of overlap
  return(mat)
}

```

## Confirm that the function is operational

```{r Test function}
#Assign labels to all inversions
Pop1$LABEL <- paste(Pop1$INDIVIDUAL,Pop1$POS_MINUS_CI,Pop1$END_PLUS_CI, sep="_")

##Test 1: Run function on chrom1 of individual 1
Pop1.chr1 <- Pop1[Pop1$CHROM == "NC_044048.1", ]
P16216.chr1 <- Pop1.chr1[Pop1.chr1$INDIVIDUAL == "16216", ]

P16216_overlap <- overlap_test(P16216.chr1)
  #SUCCESS

#Test 2: Run function on chrom1 across individuals
Pop1_names <- unique(Pop1.chr1$INDIVIDUAL)

for(i in 1:length(Pop1_names)){
  individual <- Pop1_names[i]
  Pop.chr1 <- Pop1.chr1[Pop1.chr1$INDIVIDUAL==individual, ]
  assign(paste("P",individual,"overlap", sep=''), overlap_test(Pop.chr1))
}
  #SUCCESS
```